apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-devsecops-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-devsecops
  template:
    metadata:
      labels:
        app: flask-devsecops
    spec:
      containers:
      - name: flask-devsecops
        image: flask-devsecops:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000